plugins {
    id 'com.android.application'
}

android {
    compileSdk 37

    defaultConfig {
        applicationId "com.xhy.xp.softaphelper"
        minSdk 26
        targetSdk 37
        versionCode 1103
        versionName "1.100"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.xhy.xp.softaphelper'
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    implementation 'io.github.libxposed:service:102.0.0'
}
